name: Periodic healthcheck

on:
  push:
    branches: -dev

jobs:
  periodic_healthcheck:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v2
      with:
        url: https://${{secrets.HEROKU_APPLICATION_NAME}}.herokuapp.com/health



